### ISSUE TITLE
yaml structure example for `private`

### ISSUE THREAD

**Issue by lukehinds** [dlorenc/chains#1]
hi @dlorenc 

I am at the following section `kubectl edit secret signing-secrets -n tekton-pipelines`

Do you have an example for `kind: Secret` that shows the yaml structure using `private:`?

**Comment by font** [comment]
@lukehinds Here's an example:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: signing-secrets
  namespace: tekton-pipelines
  labels:
    pipeline.tekton.dev/release: devel
type: Opaque
data:
  private: cHJpdmF0ZSBrZXk=
  passphrase: cGFzc3dvcmQ=
```
